name: flutter_unit
description: All Platform Flutter Experience App.
publish_to: none
version: 3.2.3+2006
author: 张风捷特烈 <1981462002@qq.com>
homepage: https://juejin.cn/user/149189281194766/posts

environment:
  sdk: ">=3.5.0 <4.0.0"
workspace:
  - modules/basic_system/app
  - modules/basic_system/app_update
  - modules/basic_system/authentication
  - modules/basic_system/components
  - modules/basic_system/l10n
  - modules/basic_system/storage
  - modules/basic_system/toly_ui
  - modules/basic_system/utils

  - modules/knowledge_system/algorithm
  - modules/knowledge_system/artifact
  - modules/knowledge_system/awesome
  - modules/knowledge_system/layout

  - modules/painting_system/draw_system

  - modules/tools_system/treasure_tools

  - modules/widget_system/widget_module
  - modules/knowledge_system/note
  - modules/knowledge_system/mqtt

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # 路由与状态管理
  go_router: ^14.2.0 # 路由管理
  flutter_bloc: ^8.1.6 # 状态管理

  ## fx 架构
  fx_platform_adapter: 0.0.3 # 平台适配器
  fx_go_router_ext: 0.0.6+1 # 路由
  fx_dao: 0.0.3+4
  fx_dio: 0.0.4+3
  fx_boot_starter: 0.1.1 # app 启动器
  fx_trace: 0.0.5+5 # 异常追踪/监听

  # 数据与持久化
  dio: ^5.4.3+1 # 网络请求
  shared_preferences: ^2.5.3 # xml 固化
  jwt_decoder: ^2.0.1 # jwt 解析
  path_provider: ^2.1.5 # 路径

  # 平台功能
  #  connectivity_plus: ^6.1.4 # 网络状态
  url_launcher: ^6.3.1 # url
  archive: ^4.0.6 # 解压
  file_picker: ^10.1.9 # 文件选择器
  share_plus: ^10.1.4 # 文字分享
  package_info_plus: 8.1.4

  # 视图展示
  tolyui: 0.0.4+10 # tolyui
  tolyui_refresh: 0.0.1+1 # 下拉刷新

  dash_painter: ^1.0.2 # 虚线
  flutter_star: ^1.0.2 # 星星组件
  flutter_spinkit: ^5.2.0 # loading
  toggle_rotate: ^1.0.1 # 点击旋转
  wrapper: ^1.0.2 # 气泡包裹
  webview_flutter: ^4.2.4 # webview
  flutter_markdown: ^0.7.2+1 # markdown
  flutter_svg: ^2.0.17 # svg 展示

  # 逻辑处理
  image: ^4.0.17 # 图像处理
  equatable: ^2.0.5 # 相等辅助
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  web: ^1.0.0
  intl: 0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    #    - assets/data/web/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/article.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/toly_icon.ttf
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.ttf

toly:
  icon:
    src_zip: ""
    assets_dir: "assets/iconfont"
    file_dist: "packages/app/lib/app/res/toly_icon.dart"
